#!/usr/bin/env python3
"""Generate data/golf_balls.js from the canonical data/golf_balls.csv.

The CSV is the single source of truth. The web app loads the generated JS file so
it works when opened directly from disk (file://) without needing a web server.

Usage:
    python3 scripts/build_data.py
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "data", "golf_balls.csv")
JS_PATH = os.path.join(ROOT, "data", "golf_balls.js")

# Columns that should be parsed as numbers.
NUMERIC = {
    "year",
    "pieces",
    "compression",
    "swing_speed_min_mph",
    "swing_speed_max_mph",
    "price_usd",
}


def load_rows():
    with open(CSV_PATH, newline="", encoding="utf-8") as fh:
        rows = []
        for row in csv.DictReader(fh):
            parsed = {}
            for key, value in row.items():
                value = (value or "").strip()
                if key in NUMERIC:
                    parsed[key] = int(value) if value else None
                else:
                    parsed[key] = value
            rows.append(parsed)
        return rows


def main():
    rows = load_rows()
    payload = json.dumps(rows, indent=2, ensure_ascii=False)
    banner = (
        "// AUTO-GENERATED by scripts/build_data.py from data/golf_balls.csv.\n"
        "// Do not edit by hand; edit the CSV and re-run the script.\n"
    )
    with open(JS_PATH, "w", encoding="utf-8") as fh:
        fh.write(banner)
        fh.write("window.GOLF_BALLS = ")
        fh.write(payload)
        fh.write(";\n")
    print(f"Wrote {len(rows)} balls to {os.path.relpath(JS_PATH, ROOT)}")


if __name__ == "__main__":
    main()
